### PR TITLE
GH Action/Script changes

### PR DESCRIPTION
**Pull request by emmanvg**
- Removed and added .gitignore entry for /test directory
- Tweaks to README.rst
- Breakdown GH Action steps to prevent failure when no changes are present to be committed
- Use GH identity in commits, add date in commit message
- validate_content.py when no repo_dir is given will call `git status` to determine any recent .json modified or new files for validation

Note: Most likely if not merged before midnight it will have a `github-actions` commit...

### CODE REVIEW

**Comment by emmanvg** [comment]
My tests can be seen here: https://github.com/emmanvg/cti-stix-common-objects/actions/workflows/cve-daily-update.yml?query=branch%3Aaction-changes

**Comment by emmanvg** [comment]
reduced overall Action time ~13 mins down to ~2 mins

**Comment by rpiazza** [comment]
Maybe I'm reading this incorrectly - but should line 41 of validate_content.py be a "if not..."

**Comment by emmanvg** [comment]
you are correct...

**Pull request merged**
