### PR TITLE
move extensions dir to extension-definition

### PR DESCRIPTION
**Pull request by rpiazza**
The names of the directories in the objects directory are the full object type names, so I changed extensions to extension-definition

### CODE REVIEW

**Comment by rpiazza** [comment]
@ejratl - can you do a quick merge of this PR?

Do you think it is something that needs to be broadcast on the cti email list?

**Comment by ejratl** [comment]
@rpiazza I don't understand your comment - why does the directory name need to be changed? I do think that this should probably be explained on the mailing list, since it may impact some tools.

**Comment by rpiazza** [comment]
The objects directory contains common objects.  Each subdirectory is named after the object type in STIX.  The object type is "extension-definition" NOT "extensions".  I wanted to change it for consistency.

**Comment by ejratl** [comment]
Thanks for the explanation and the PR, @rpiazza!

**Review by ejratl — APPROVED** [review]

**Pull request merged**
