### PR TITLE
adding allOf to pap schema

### PR DESCRIPTION
**Pull request by ghackford-mitre**
Adding AllOF element to JSON schema for pap extension.

### CODE REVIEW

**Comment by rpiazza** [comment]
Look at the CUI schema - this is more what I had in mind...

**Comment by adulau** [comment]
Thanks for the contribution.

`PAP` has been recently aligned with TLPv2 and now includes `PAP:CLEAR`.

https://github.com/MISP/misp-taxonomies/blob/main/PAP/machinetag.json

It would be nice if you could update the PR.

**Comment by adulau** [comment]
Thanks I would just keep both `clear` and `white` to ensure backward compatibility.

**Comment by clenk** [comment]
Looks like a good update - we'll also need to update the adoc...

**Pull request closed without merging**
