### PR TITLE
Add Identity Contact Information Extension

### PR DESCRIPTION
**Pull request by dc3-tsd**
Initial draft for identity contact information extension and renaming incident extension json schema to match new naming conventions

### CODE REVIEW

**Comment by rpiazza** [comment]
@dc3-tsd - Jeff, I think you did a c & p when you created the identity extension JSON schema - lot of stuff at the top says "incident"

**Comment by rpiazza** [comment]
@ejratl - LGTM

**Comment by ejratl** [comment]
@rpiazza Thanks for the review! @dc3-tsd Is this complete?

**Comment by dc3-tsd** [comment]
We believe so, but there seemed to be merge conflicts so the latest was pulled down and merged in before we pushed it up again.

**Pull request merged**
